# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cb50bac7921f08b183e60e77aa5829e4e439a2b761cf32852b0f6e352359ba8d2ccdc230297c215dd8a910f5f5af41e9393751d64659cf4eeb8059c26a3b08d

test:
  secret_key_base: 923a2506110ee8ef926aef601ae1d28a22deebe26fff15c19bb863595eb2e7a11d95383df507ca02e61bb6e8aabe3bcea17ff5afee92f01d6b3bae2a7477c8be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
